version: '3.8' 
services: 
  app: 
    build: . 
    ports: 
      - "8080:8080" 
    depends_on: 
      - db 
      - rabbitmq 
 
  db: 
    image: postgres:13 
    environment: 
      POSTGRES_DB: disconnected_marketplace 
      POSTGRES_USER: your_db_username # INPUT_REQUIRED {Database username} 
      POSTGRES_PASSWORD: your_db_password # INPUT_REQUIRED {Database password} 
    ports: 
      - "5432:5432" 
 
  rabbitmq: 
    image: rabbitmq:3-management 
    ports: 
      - "5672:5672" 
      - "15672:15672" 