apiVersion: v1 
kind: Service 
metadata: 
  name: rabbitmq 
spec: 
  type: ClusterIP 
  ports: 
    - port: 5672 
      targetPort: 5672 
    - port: 15672 
      targetPort: 15672 
  selector: 
    app: rabbitmq 